### ISSUE TITLE
Report fails if no bookmark in archive (old archive)

### ISSUE THREAD

**Issue by lapineige** [kensanata/mastodon-archive#98]
When used (on purpose) with a split archive, containing only old (prior to bookmark functionality) content, the `report` command fails:
```
Traceback (most recent call last):
    File "/home/user/.local/bin/mastodon-archive", line 8, in <module>
    sys.exit(main())
    File "/home/user/.local/lib/python3.10/site-packages/mastodon_archive/__init__.py", line 333, in main
    args.command(args)
    File "/home/user/.local/lib/python3.10/site-packages/mastodon_archive/report.py", line 108, in report
    bookmarks = data["bookmarks"]
    KeyError: 'bookmarks'
```

This probably lack an exception in case the key is not found.

**Comment by lapineige** [comment]
After a very quick look at the code, I guess it would be solved by adding `if "bookmarks" in data:` to the lines 108 and 115 https://github.com/kensanata/mastodon-archive/blob/main/mastodon_archive/report.py#L108 https://github.com/kensanata/mastodon-archive/blob/main/mastodon_archive/report.py#L115

**Comment by lapineige** [comment]
I tried it on the archive that triggered the issue, and on a recent one with bookmarks.
Nothing to report, maybe that's enough as a fix ?

**Comment by kensanata** [comment]
Can you take a look at e4d3cf3?

**Comment by lapineige** [comment]
Great, thanks a lot ! 😃
